apiVersion: infrastructure.platform.io/v1alpha1
kind: OpenBaoSecretStoreProvider
metadata:
  name: development-system-openbao-secret-store-provider
  namespace: development-system
spec:
  compositionSelector:
    matchLabels:
      infrastructure.platform.io/provider: openbao
      infrastructure.platform.io/deployment-mode: incluster
  parameters:
    instanceId: development-system
    infrastructureNamespace: development-system
    secretStoreName: secret-store
    secretPath: secret
    secretEngineVersion: v2
