apiVersion: infrastructure.platform.io/v1alpha1
kind: AWSSecretStoreProvider
metadata:
  name: development-system-aws-secret-store-provider
  namespace: development-system
spec:
  compositionSelector:
    matchLabels:
      infrastructure.platform.io/provider: aws-secrets-manager
      infrastructure.platform.io/deployment-mode: managed
  parameters:
    instanceId: development-system
    infrastructureNamespace: development-system
    secretStoreName: secret-store
    region: us-east-1
    serviceAccountName: default
