apiVersion: infrastructure.platform.io/v1alpha1
kind: AzureSecretStoreProvider
metadata:
  name: development-system-azure-secret-store-provider
  namespace: development-system
spec:
  compositionSelector:
    matchLabels:
      infrastructure.platform.io/provider: azure-key-vault
      infrastructure.platform.io/deployment-mode: managed
  parameters:
    instanceId: development-system
    infrastructureNamespace: development-system
    secretStoreName: secret-store
    vaultUrl: https://example-kv.vault.azure.net
    authType: WorkloadIdentity
    serviceAccountName: default
