apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: development-system-backstage-auth
  namespace: development-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: development-system-backstage-auth
    creationPolicy: Owner
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: development-system/backstage/github-oauth
        property: clientId
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: development-system/backstage/github-oauth
        property: clientSecret
