apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-system-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dynamic-systems-io/system-development.git
    targetRevision: main
    path: security
  destination:
    server: https://kubernetes.default.svc
    namespace: development-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
